//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBuster.Shared.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationEntryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationEntryResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBuster.Shared.Infrastructure.Resources.ConfigurationEntryResources", typeof(ConfigurationEntryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard Authorization header using the Bearer scheme: Example &quot;bearer {token}&quot;.
        /// </summary>
        public static string ApiKeySchemeDescription {
            get {
                return ResourceManager.GetString("ApiKeySchemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a header.
        /// </summary>
        public static string ApiKeySchemeIn {
            get {
                return ResourceManager.GetString("ApiKeySchemeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authorization.
        /// </summary>
        public static string ApiKeySchemeName {
            get {
                return ResourceManager.GetString("ApiKeySchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apiKey.
        /// </summary>
        public static string ApiKeySchemeType {
            get {
                return ResourceManager.GetString("ApiKeySchemeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a api-version.
        /// </summary>
        public static string ApiVersion {
            get {
                return ResourceManager.GetString("ApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sample API {0}.
        /// </summary>
        public static string SampleApiDescriptionFormat {
            get {
                return ResourceManager.GetString("SampleApiDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AppSettings.
        /// </summary>
        public static string SectionAppSettings {
            get {
                return ResourceManager.GetString("SectionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oauth2.
        /// </summary>
        public static string SecurityDefinitioOAuth2 {
            get {
                return ResourceManager.GetString("SecurityDefinitioOAuth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AppSettings:Secret.
        /// </summary>
        public static string ValueAppSetings {
            get {
                return ResourceManager.GetString("ValueAppSetings", resourceCulture);
            }
        }
    }
}
