//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBuster.Shared.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBuster.Shared.Infrastructure.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of entries of Body and Rules doesn&apos;t match.
        /// </summary>
        public static string DomainEventValidateBodyAndRulesEntriesCountNotMatch {
            get {
                return ResourceManager.GetString("DomainEventValidateBodyAndRulesEntriesCountNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid key in {0} {1} event.
        /// </summary>
        public static string DomainEventValidateBodyKeysErrorMessage {
            get {
                return ResourceManager.GetString("DomainEventValidateBodyKeysErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} didn&apos;t pass the rule validation in {1} event.
        /// </summary>
        public static string DomainEventValidateBodyRulesErrorMessage {
            get {
                return ResourceManager.GetString("DomainEventValidateBodyRulesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} attribute must not be empty.
        /// </summary>
        public static string InvalidAttributeExceptionFromEmpty {
            get {
                return ResourceManager.GetString("InvalidAttributeExceptionFromEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length of {0} should be exaclty {1} characters.
        /// </summary>
        public static string InvalidAttributeExceptionFromLength {
            get {
                return ResourceManager.GetString("InvalidAttributeExceptionFromLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length of {0} cannot exceed {1} characters.
        /// </summary>
        public static string InvalidAttributeExceptionFromMaxLength {
            get {
                return ResourceManager.GetString("InvalidAttributeExceptionFromMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length of {0} cannot be less than {1} characters.
        /// </summary>
        public static string InvalidAttributeExceptionFromMinLength {
            get {
                return ResourceManager.GetString("InvalidAttributeExceptionFromMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} attribute is invalid because of its value: {1}.
        /// </summary>
        public static string InvalidAttributeExceptionFromValue {
            get {
                return ResourceManager.GetString("InvalidAttributeExceptionFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^(\{{0,1}([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}\}{0,1})$.
        /// </summary>
        public static string UUIDV4PATTERN {
            get {
                return ResourceManager.GetString("UUIDV4PATTERN", resourceCulture);
            }
        }
    }
}
