//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBuster.IAM.Domain.TokenAggregate.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBuster.IAM.Domain.TokenAggregate.Resources.TokenResources", typeof(TokenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a created_at.
        /// </summary>
        public static string FieldCreatedAt {
            get {
                return ResourceManager.GetString("FieldCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hash.
        /// </summary>
        public static string FieldHash {
            get {
                return ResourceManager.GetString("FieldHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a updated_at.
        /// </summary>
        public static string FieldUpdatedAt {
            get {
                return ResourceManager.GetString("FieldUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user_id.
        /// </summary>
        public static string FieldUserId {
            get {
                return ResourceManager.GetString("FieldUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a country_code.
        /// </summary>
        public static string PayloadCountryCode {
            get {
                return ResourceManager.GetString("PayloadCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a country_id.
        /// </summary>
        public static string PayloadCountryId {
            get {
                return ResourceManager.GetString("PayloadCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        public static string PayloadEmail {
            get {
                return ResourceManager.GetString("PayloadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a first_name.
        /// </summary>
        public static string PayloadFirstName {
            get {
                return ResourceManager.GetString("PayloadFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a last_name.
        /// </summary>
        public static string PayloadLastName {
            get {
                return ResourceManager.GetString("PayloadLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a role.
        /// </summary>
        public static string PayloadRole {
            get {
                return ResourceManager.GetString("PayloadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user_id.
        /// </summary>
        public static string PayloadUsedId {
            get {
                return ResourceManager.GetString("PayloadUsedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User has already a Token..
        /// </summary>
        public static string ValidationUserHasToken {
            get {
                return ResourceManager.GetString("ValidationUserHasToken", resourceCulture);
            }
        }
    }
}
